'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DediAlum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="DediAlum.HorasAlumnosSoap")>  _
    Public Interface HorasAlumnosSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento asig del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Hesti", ReplyAction:="*")>  _
        Function Hesti(ByVal request As DediAlum.HestiRequest) As DediAlum.HestiResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Hesti", ReplyAction:="*")>  _
        Function HestiAsync(ByVal request As DediAlum.HestiRequest) As System.Threading.Tasks.Task(Of DediAlum.HestiResponse)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento asig del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Hreal", ReplyAction:="*")>  _
        Function Hreal(ByVal request As DediAlum.HrealRequest) As DediAlum.HrealResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Hreal", ReplyAction:="*")>  _
        Function HrealAsync(ByVal request As DediAlum.HrealRequest) As System.Threading.Tasks.Task(Of DediAlum.HrealResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Diferencia", ReplyAction:="*")>  _
        Function Diferencia(ByVal hesti As Integer, ByVal hreal As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Diferencia", ReplyAction:="*")>  _
        Function DiferenciaAsync(ByVal hesti As Integer, ByVal hreal As Integer) As System.Threading.Tasks.Task(Of Integer)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HestiRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Hesti", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As DediAlum.HestiRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As DediAlum.HestiRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HestiRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public asig As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public email As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal asig As String, ByVal email As String)
            MyBase.New
            Me.asig = asig
            Me.email = email
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HestiResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HestiResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As DediAlum.HestiResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As DediAlum.HestiResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HestiResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public HestiResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HestiResult As Integer)
            MyBase.New
            Me.HestiResult = HestiResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HrealRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Hreal", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As DediAlum.HrealRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As DediAlum.HrealRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HrealRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public asig As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public email As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal asig As String, ByVal email As String)
            MyBase.New
            Me.asig = asig
            Me.email = email
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HrealResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HrealResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As DediAlum.HrealResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As DediAlum.HrealResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HrealResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public HrealResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HrealResult As Integer)
            MyBase.New
            Me.HrealResult = HrealResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface HorasAlumnosSoapChannel
        Inherits DediAlum.HorasAlumnosSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class HorasAlumnosSoapClient
        Inherits System.ServiceModel.ClientBase(Of DediAlum.HorasAlumnosSoap)
        Implements DediAlum.HorasAlumnosSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DediAlum_HorasAlumnosSoap_Hesti(ByVal request As DediAlum.HestiRequest) As DediAlum.HestiResponse Implements DediAlum.HorasAlumnosSoap.Hesti
            Return MyBase.Channel.Hesti(request)
        End Function
        
        Public Function Hesti(ByVal asig As String, ByVal email As String) As Integer
            Dim inValue As DediAlum.HestiRequest = New DediAlum.HestiRequest()
            inValue.Body = New DediAlum.HestiRequestBody()
            inValue.Body.asig = asig
            inValue.Body.email = email
            Dim retVal As DediAlum.HestiResponse = CType(Me,DediAlum.HorasAlumnosSoap).Hesti(inValue)
            Return retVal.Body.HestiResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DediAlum_HorasAlumnosSoap_HestiAsync(ByVal request As DediAlum.HestiRequest) As System.Threading.Tasks.Task(Of DediAlum.HestiResponse) Implements DediAlum.HorasAlumnosSoap.HestiAsync
            Return MyBase.Channel.HestiAsync(request)
        End Function
        
        Public Function HestiAsync(ByVal asig As String, ByVal email As String) As System.Threading.Tasks.Task(Of DediAlum.HestiResponse)
            Dim inValue As DediAlum.HestiRequest = New DediAlum.HestiRequest()
            inValue.Body = New DediAlum.HestiRequestBody()
            inValue.Body.asig = asig
            inValue.Body.email = email
            Return CType(Me,DediAlum.HorasAlumnosSoap).HestiAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DediAlum_HorasAlumnosSoap_Hreal(ByVal request As DediAlum.HrealRequest) As DediAlum.HrealResponse Implements DediAlum.HorasAlumnosSoap.Hreal
            Return MyBase.Channel.Hreal(request)
        End Function
        
        Public Function Hreal(ByVal asig As String, ByVal email As String) As Integer
            Dim inValue As DediAlum.HrealRequest = New DediAlum.HrealRequest()
            inValue.Body = New DediAlum.HrealRequestBody()
            inValue.Body.asig = asig
            inValue.Body.email = email
            Dim retVal As DediAlum.HrealResponse = CType(Me,DediAlum.HorasAlumnosSoap).Hreal(inValue)
            Return retVal.Body.HrealResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DediAlum_HorasAlumnosSoap_HrealAsync(ByVal request As DediAlum.HrealRequest) As System.Threading.Tasks.Task(Of DediAlum.HrealResponse) Implements DediAlum.HorasAlumnosSoap.HrealAsync
            Return MyBase.Channel.HrealAsync(request)
        End Function
        
        Public Function HrealAsync(ByVal asig As String, ByVal email As String) As System.Threading.Tasks.Task(Of DediAlum.HrealResponse)
            Dim inValue As DediAlum.HrealRequest = New DediAlum.HrealRequest()
            inValue.Body = New DediAlum.HrealRequestBody()
            inValue.Body.asig = asig
            inValue.Body.email = email
            Return CType(Me,DediAlum.HorasAlumnosSoap).HrealAsync(inValue)
        End Function
        
        Public Function Diferencia(ByVal hesti As Integer, ByVal hreal As Integer) As Integer Implements DediAlum.HorasAlumnosSoap.Diferencia
            Return MyBase.Channel.Diferencia(hesti, hreal)
        End Function
        
        Public Function DiferenciaAsync(ByVal hesti As Integer, ByVal hreal As Integer) As System.Threading.Tasks.Task(Of Integer) Implements DediAlum.HorasAlumnosSoap.DiferenciaAsync
            Return MyBase.Channel.DiferenciaAsync(hesti, hreal)
        End Function
    End Class
End Namespace
